// 1800-word list. One category per line:  Category|word,word,word
const WORDS_1800 = `Days of the week|Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Weekday,Weekend
Months of the year|January,February,March,April,May,June,July,August,September,October,November,December
Colours|Red,Blue,Green,Orange,Yellow,Indigo,Violet,Purple,Black,White,Grey,Gold,Silver,Beige,Pink,Mustard,Lavender,Mauve,Peach,Coral,Tan,Teal,Cyan,Rust,Charcoal,Cream,Maroon,Olive
Subjects|MBA,MBBS,Business management,Arts,Science,Journal,Engineering,Finance,Commerce,Accounting,History,Architecture,Computer science,IT,Creative arts,Politics,Philosophy,Biology,Visual arts,Performing arts,Chemistry,Humanities,Agriculture,Statistics,Mathematics,Physical education,Psychology,Sociology,Victimology,Criminology,Logic
Studying at college/university|Vocabulary,Student support system,Student retention,Admission,Guidelines,Principal,Staff,Lecturers,Proofreading,Experiment,Written work,Book,Notes,Stationery items,Printing,Photocopy,Course outline,Syllabus,Programs,Outreach,Group discussion,Seminar,Handout,Research,Dissertation,Research paper,Report writing,Experience,Reference,Textbook,Homestay,Speech,Laptop,Printer,Assessment,Library,Study room,Canteen,Module,Teamwork,Topic,Main hall,Student advisor,Specialist,Shelves,Dining,Primary,Secondary,Intermediate,Media outlet,Advanced,Introduction,Background,Profile,Pencil,Eraser,Higher education,Overseas,Study abroad,Passport,Compound,Campus,International student,Commencement,College,University,Give a talk,Knowledge,Diploma,PG,UG,Reunion,Outcomes,Results
Numbers|One,Two,Three,Four,Five,Six,Seven,Eight,Nine,Ten,Hundred,Thousand
Continents|Asia,Africa,North America,South America,Europe,Australia,Antarctica
Countries|China,Brazil,New Zealand,Zimbabwe,India,South Africa,Portugal,Argentina,England,Australia,Ireland,Netherlands,Norway,Sweden,Dubai,Russia,United States of America,USA,Canada,Egypt,Mexico,Germany,Malaysia,Pakistan,Singapore,Philippines,Denmark,Scotland,North Korea,Turkey,Greece
Languages|Russian,Thai,Persian,French,English,Tamil,Greek,Italian,Punjabi,Hindi,Bengali,Malayalam,Telugu,Rajasthani,Marathi,German,Japanese,Chinese,Spanish,Mandarin,Portuguese,Filipino
Transportation|Sailboat,Punt,Airport,Aircraft,Car,Bus,Train,Ship,Crew,Passenger,Helicopter,Seaplane,Cabin cruiser,Kayak,Canoe,Gondola,Cargo,Shipment,Container,Ferry,Liner,Canal boat,Narrow boat,Dinghy sailing,Hovercraft,Hydrofoil,Airship,Hot-air balloon,Platform,Automobile
Workplaces|Clinic,Stress,Recognition,Awards,Achievement,Employer,Employment,Cooperation,Team leaders,Showroom,Fired,Layoff,Workshop,Conferences,Meeting,Reception,Appointment,Rejection,Colleague,Vision,Mission,Ability,Skill set,Internship,Tribute,Pioneer,Contribution,Blaze a trail,Symbol,Legend,Personality,Determined,Forgetful,Diligent,Wear out,Perseverance,Workaholic,Workload,Struggle,Continuous exploration,Hard-working,Get along with,Proposal,Branch,Transaction,Bid,Transfer,Job hunting,Inexperienced,Want ads,Unemployment,Wage,Opening,Inquiry,Do odd jobs,Consult,Application letter,Fire,Hire,Job-hopping,Impression,Pressure,Turn down,Confident,Confidential,Have no match for,Manager,Consulting firm
Places|Accommodation,Local library,Swimming pool,Dance studio,Park,Conversation club,Kindergarten,Parliament,Assembly,Cafeteria,Cottage,Resting area,Restaurant,Bookshop,Sports centre,Central hall,City council,Cafe shop,Home
Money matters|Retail,Voucher,Coupon,Money,Exchequer,Cash flow,Low risk,Management,Credit,Debit card,Cheque,Annual fee,Poverty,Bank statement,Current account,Deficit,Inflation,MasterCard,UPI,VISA,Duty-free store,Paytm,Distribution costs,Finance department,Family finances,Student’s account,Deposit,Withdraw,Counterfeit money,Debt,Grace period,In advance,Budget deficit,Interest,Free money,Partial refund,Purchase,Cash,Advancement,Tuition fees,Income,Non-refundable,Interest rate,Annuity,Public money,Taxpayers,Financial management,Client
Verbs|Touch,Learn,Suggest,Arrange,Borrow,Persuade,Hunt,Support,Register,Train,Supervise,Edit,Revise,Walk,Run,Jump,Exercise,Perform,Concentrate,Focus,Study,Immigrate,Review,Fight,Compete,Withstand,Face it
Hobbies|Gardening,Painting,Embroidery,Chess,Carrom,Cycling,Parachute,Scuba diving,Skateboarding,Stamp collection,Crafting,Sculpting,Ice skating,Golf,Billiards,Photography,Bowls,Snorkelling,Pottery,Woodcarving,Musician
Marketing|Profit,Loss,Margin,Competition,Competitor,Merchandise,Recruitment,Cataloguing,Interview,Downfall,Risk management,Research method,Research analysis,Entertainment,Industry,TV program,Newspaper offer,Special discounts,Leadership strategy,Mass media,Marketing,Questionnaire,Products,Best quality,Survey,Poll,Business training,Statistics,Bankrupt,Circulation,Financier surplus,Economic crisis,Potential,Cyberspace,Collapse,Multimedia,Hacker,Server,Monetisation,Quarterly,Half-yearly,Marriage,Tendency,Percentage
Adjectives|Permanent,Temporary,Convenient,Immense,Vast,Salty,Extinct,Vulnerable,Pessimistic,Western,Realistic,Optimistic,Suitable,Social,Ancient,Fantastic,Exciting,Compulsory,Flexible,Confident,Intact,Various,Decisive,Practical,Knowledgeable,Tranquil,Conscious,Commitment,Recessionary,Boring,Modern
Sports|Exercise,Warm up,Spirit,Jet-skiing,Bodyboarding,Snowboarding,Players,Sportsmanship,Cricket,Baseball,Basketball,Rugby,Hang-gliding,Skydiving,Soccer,American football,Hockey,Goals,Draw,Swimming,Tennis,Squash,Javelin,Badminton,Shuttle,Ping-pong,Field,Court,Cricket match,Weather,Pitch,Stadium,Team,Discus,Hammer,High jump,Horse racing,Show jumping,Polo,Cycling,Canoeing,Refreshment,Gymnasium,Extreme sports,Paragliding,Abseiling,Athlete,Gym,Workout,Bungee jumping,White-water rafting,Surfing,Windsurfing,Kitesurfing,Mountain biking,Push-up,Pull-up,Bullet squads,Judo,Recreation,Jogging,Press-up,Snooker,Walking,Barbell,Treadmill,Winner,Runner-up,Championship,Doing Dutch
Shapes|Square,Rectangle,Mass,Depth,Shallow,Round,Oval,Triangle,Parallelogram,Trapezium,Cylindrical,Three dimensions,Measurement,Spiral,Metric system,High,High frequency,Height,Breadth,Length,Altitude,Imperial system,Curved,Spherical,Circle,Polygon,Decoration
Weather|Moist,Rainy,Sunny,Hot,Humid,Breezy,Chill,Cold,Winter,Dusty,Freezing,Warm,Wet,Antenna,Forecast,Sunrise,Dry,Cloudy,Heat wave,Overcast,Shower,Tornado,Sunset,Temperature,Pressure,Precipitation,Erosion,Climate trend,Variation,Climate warming,Watch,Sensitive,Vulnerable,Anomaly,Mishap,Conservation area,Gust,Downpour,Recycled water,Renewable energy,Feeling under the weather
Equipment and tools|Mechanic,Light,Screw,Equipment,Technician,Electricity,Wiring,Helmet,Safety,Musical instrument,Cassette,Digital,Silicon chip,Screen,Brakes,Wheels,Pencil,Disk,Backpack,Electronic gadgets,Device,Monitor,Computer,Laptop,PC,Tablet,Appliance,Gizmo,Machinery,Mechanism,Gear,Apparatus,Utensils,Instruction,Hardware,Stuff
Arts and media|Graphics,Design,Classical music,Theatre,Cinemas,Art gallery,Gallery,Museum,Ballet,Television,Radio,Newspaper,Opera,Orchestra,Concert,Symphony,Press,Publication,Publisher,Paperback,Hardcover,Conflict,Campaign,Conductor,Vocalist,Festival,Carnival,Exhibition,Publishing,Announcement,Cable,Communication,Correspondence,Artistry,Craftsmanship,Dexterity,Expertise,Beverage,Horror films,Documentary,Violence movie,Commercial advertisement,Romantic songs,Friendly gesture,TV theatre,Entertainment industry,Film business,Gardening,Assignment
Vehicles|Camper,Double-decker bus,Car,Bus,Single-decker,Tow truck,Lorry,Ferry,Truck,Tram,Underground,Subway,Caravan,Tractor,Steam train,Freight train,Jeep,Taxi,Automobile,Auto rickshaw,Breakdown truck,School,College bus,Vehicle,Cab,Transportation,Transporter,Pickup,Drop by,Forklift truck,Air conditioner,Sink,Install
Expressions and time|Days,Part-time,Full-time,Three times,Once,Twice,Thrice,Per week,Millennium,A gap,Midnight,Century,Decade,Fortnight,Indexing
Materials|Silver,Gold,Paper,Wood,Aluminium,Copper,Glass,Leather,Bone,Lumber/wood,Glue,Concrete,Wax,Fur,Metal,Rubber,Plastic,Ceramics,Cement,Stone,Textile,Composite,Fibreglass,Feather,Cotton,Silk,Titanium,Platinum,Steel,Raw materials
Other words|Ultrasound,Spelling,Recipient,Activity,Attitude,Farewell,Encouragement,Encyclopedia,Robot,Artificial intelligence,Proficiency,Evolution,Revolution,Man-made,Narrative,Dialogue,Passport,Guarantee,Procedures,Safety road,Driving licence,Prize,Ramification,Observation,Nature conservation,Life expectancy,Videos,Liberty,Republic,Opportunity,Dialect,Frequency,Calendar,Burger,Foodie,Junior,Senior,Prototype,Fulfilment,Government,Creativity,Umbrella,Nature,Original inhabitant,Indigenous,Demonstration,Circuit,Decision-making,Language test,Tests,Exams,Alternatives,Visa sponsorship,Chocolate,Biscuits,Commerce,Epidemic,Pandemic,Bird flu,SARS,Toothache,Allergy,Sneeze,Fracture,Diabetes,Sore throat,Runny nose,Infectious illness,Have a temperature check,Dental decay,Cure,Recover,Solar
Health|Nursery,Tomatoes,Pizza,Bread,Cereals,Minerals,Zinc,Meat,Food,Fruits,Vegetables,Yoghurt,Beans,Milk,Cheese,Liver,Chicken,Mutton,Beef,Pork,Treatment,Medicine,Remedy,Workout,Regular exercise,Nursing,Health care,Eggs,Disease,Tai-chi,Fitness,Health-fit,Balanced diet,Food pyramid,Vitamin,Rice,Carbohydrates,Green pepper,Chilly,Blackcurrant,Mango,Pineapple,Orange,Well-being,Robustness,Soundness,Verdure,Wellness,Healthiness,Sap,Body mass index,Biopsy,Hypotension,Anti-inflammatory,Put on weight,Watch your diet,Overweight,Lose weight,Physical exercise,On diet,In good shape,In a fit state,Feel under the weather,In poor shape,Fit as a fiddle,Out of shape,Hospital,Doctors,Physician,Surgeon,Consultant,Clinic,Anaesthetist,Infirmary
Jobs and work|Lecturer,Vacancy,Teacher,Professor,Address,Mail,Pilot,Creator,Cashier,Captain,Engineer,Assistant,Associate,Executive,Chief executive officer,Accountant,Guard,Security,Flight attendant,Specialist,Data analyst,Curriculum vitae,Resume,Clerk,Freelance,Professional experience,Volunteer,Craftsman,Waitress,Psychologist,Software developer,Menial jobs,Director,Senior role,Junior post,Situation,Employ,Career,Profession,Occupation,Spot,Employment,Place,Capacity,Skills required,Office space,Service,Pursuit,Mission,Practice,Engagement,Determination,Success
Nature and animal kingdom|Landscape,Mountains,Valley,River,Forest,Earthquake,Tsunami,Footbridge,Field,Desertification,Cliff,Island,Volcano,Catastrophe,Natural calamity,Disaster,Oasis,Dam,Canyon,Avalanche,Tornado,Lake,Reef,Coast,Waterfall,Village,Town,Storm,Flood,Hurricane,Pond,Peninsula,Hill station,Typhoon,Beach,Cave,Countryside,Desert,Environment,Nature,Meadow,Ocean,Sea,Wild,Animal,Birds,Branch,Bush,Fish,Flower,Grass,Insects,Mud,Path,Sand,Trees,Wave,Wildlife,Earth,Planet,Tiger,Lion,Seabirds,Mammals,Genus,Reptile,Octopus,Amphibian,Family,Livestock,Stem,Roots,Cluster,Fertiliser,Core,Bark,Trunk,Twig
Environment|Coal,Greenhouse gas,Fossil fuels,Acid rain,Global warming,Drought,Contaminated,Effect,Power plants,Deforestation,Afforestation,Solar panels,Solar power,Hydroelectric power,Environmentally friendly,Oxygen,Carbon dioxide,Chemical-free,Vegetation,Sea level rise,Ocean currents,Soil conditioner,Burning fossil fuels,Fumes,Climate,Pollution,Energy source,Nitrogen,Smog,Temperature,Firewood,Atmosphere,Biodiversity,Carbon monoxide,Carcinogen,Biodegradable,Biogas
Homes|Ground floor,Oven,Hallway,Insurance,Story,Kitchen,Houseboat,Duplex,Penthouse,Bungalow,Thatched cottage,Mobile home,A block of flats,Apartment building,Rent,Lease,Sofa,Coffee table,Condominium,Basement,Terraced house,Tenant,Row house,Diggins,Dwelling,Fireside,Habitation,Hearthstone,Bathroom,Abode,Dollhouse,Cabin,Household,Edifice,Guesthouse,Residence,Maisonette,Downtown,Auburn,Spare room,Subway,Housing,Entrance,House-warming party,Transportation,Burglar,Neighbourhood,Dwell,Apartment,Flat,Sideway,Terrace,Landlord,Landlady,Accommodation,Vacuum cleaner,Housework,Household costs,Economical,Frugal,Keep an eye on,Date,Hospitality,Hospitable
Rating and qualities|Cheap,Expensive,Rich,Poor,Satisfactory,Dangerous,Disappointment,Efficient,Luxurious,Spotted,Striped,Recommended,Reasonable,Safe,Quantity,Quality,Kind,Aspect,Condition,Character,Superior,Exclusive,Offers,First-rate,Prime,Excellent,Top-notch,Topflight,Five-star,Budget
Touring and backpacking|Tour,Excursion,Trip,Guide,Ticket fee,Office,Destination,Arrival,Departure,Reservation,Cancellation,Advance booking,Double occupancy,Rooms and accommodations,Nearby tourist attractions,Spots,Souvenir,Picnic,Aquarium,Suite,Memorable,Hostel,Culture,View,Scenic,Motel,Check in,Flight number,Travel agency,Book the ticket,Resort,Express fast,High-speed,Shuttle,Tube,Underground,Expressway,Freeway,Roundtrip,Skiing,Streetcar
Library|Shelf,Librarian,Copier,Overdue,Reading room,Reference,Periodical room,Return,Magazine,Fine,The stacks,Index,Catalogue,Study lounge,Library card,Book reservation,Back issue,Current issue,Latest number,Keyword,Writing permission,Check out,Put on reserve,Volume,Study,Book room,Storage,Media centre,Information desk,Atheneum,Elective
School|Student,Freshman,Sophomore,Bachelor,Master,Doctoral candidate,Alumni,Alumnus,Post doctorate,Dean,Rank,Curriculum,Seminar,Drop-out,Physics,Computer,Makeup exam,Book review,Novel,Press,Biography,Editorial,Extra copy,Registration,Enrolment,Paperback edition,Out of print,Plough through,Read,Write extensively,Get through a novel,Be addicted to the book,Speech contest,Competition,Sign up for,Enrol in,Future students
Shopping|Department store,Receipt,Outlet,Sell out,Grocery store,Customer,Complaint,Deliver,Convenience store,Mall,Chain store,Supermarket,Family size,On sale,Electronic product,Stationery,Digital,Past the prime,Video camera,Housework,Electric cooker,Iron,Budget,Economical,Fix the dinner,Keep an eye on
City|Leisure time,Date,Pay phone,Long-distance call,Take a message,Hold on,Hospitable,Telephone booth,Hang up,Maintenance,Install,Crack,Unfurnished,Baby crib,Multiple glazing,Sideboard,Sink,Heater,Refrigerator,Fridge,Pipe,Furnace,Leak,Air conditioner,Plumber`;
