// 1200-word list. One category per line:  Category|word,word,word
const WORDS_1200 = `Days of the week|Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Weekdays,Weekend
Months of the year|January,February,March,April,May,June,July,August,September,October,November,December
Money matters|Cash,Debit,Credit card,Cheque,In advance,Annual fee,Monthly membership,Interest rate,Deposit,Tuition fees,Poverty,Bank statement,Money management,Current account,Student account,Withdraw,Low-risk investment,Mortgage,Grace period,Budget deficit,Retail voucher,Coupon,Counterfeit money,Public money,Taxpayers’ money,Debt,Interest-free credit,Purchase,Partial refund,Annuity,Non-refundable,MasterCard,VISA,Distribution costs,Income,Finance department,Family finances,Duty-free store
Subjects|Science,Politics,History,Biology,Architecture,Law,Geography,Archaeology,Literature,Business management,Agriculture,Statistics,Mathematics,Logic,Physics,Psychology,Anthropology,Economics,Philosophy,Performing arts,Visual arts,Chemistry,Humanities
Studying at college/university|Course outline,Group discussion,Handout,Written work,Report writing,Research,Proofreading,Experiment,Experience,Reference,Textbook,Dictionary,Laptop,Printer,Student advisor,Teamwork,Module,Topic,Assessment,Library,Department,Computer centre,Classroom,Lecture,Tutor,Main hall,Attendance,Deadline,Give a talk,Speech,Computer laboratory,Certificate,Diploma,Placement test,Overseas students,Full-time,Facilities,College,Dining room,Specialist,Knowledge,International,Accommodation,Homestay,Primary,Secondary,Intermediate,Media room,Resources room,Staff,Commencement,Dissertation,Leaflet,Faculty,Pupils,Pencil,Feedback,Tasks,Outcomes,Advanced,Introductory,Extra background,Higher education,Guidelines,Post-secondary,Supervisor,Bachelor's degree,Compound,Vocabulary,Student support services,Student retention,Publication,Foreign students,Schedule,School reunion,Registrar’s office,Stationery
Marketing|Catalogue,Interview,Newsletter,Competition,TV program,Strategies,Research method,Entertainment industry,Leadership,Management,Display,Products,Customer,Special offer,Collecting data,Questionnaire,Survey,Mass media,Statistic,Profit margin,Poll,Business card,Training,Trainee,Merchandise,Manufacture,Recruitment
Health|Yoga,Tai-chi,Keep-fit,Salad bar,Vegetarian,Outdoor activities,Leisure time,Disease,Meal,Protein,Balanced diet,Food pyramid,Vitamin,Carbohydrates,Rice,Pasta,Potatoes,Pizza,Tomatoes,Bread,Cereals,Minerals,Zinc,Meat,Seafood,Eggs,Beans,Milk,Cheese,Yoghurt,Fruit,Vegetables,Citrus fruits,Green pepper,Blackcurrant,Nuts,Egg yolk,Liver,Medicine,Treatment,Remedy,Nursing care,Nursery,Regular exercise
Nature|Field,Footbridge,Environment,Waterfall,River,Mountain,Forest,Village,Coast,Reef,Lake,Valley,Hill,Cliff,Island,Peninsula,Earthquake,Avalanche,Tornado,Typhoon,Desertification,Volcano,Disaster,Catastrophe,Erosion,Landslides,Storm,Flood,Hurricane,Pond,Jungle,Oasis,Dam,Canyon
The environment|Greenhouse effect,Acid rain,Global warming,Carbon dioxide,Burning fossil,Exhaust fumes,Deforestation,Nitrogen oxide,Smog,Climate,Pollution,Temperature,Power plants,Landfill,Cattle,Wind turbine,Solar power,Hydroelectric power,Renewable,Source of energy,Reliable,Solar panels,Environmentally friendly,Oxygen,Chemical-free,Desert,Degradation,Vegetation,Sea level,Ocean currents,Soil conditioner,Coal,Fossil fuels,Firewood,Drought,Contaminated
The animal kingdom|Birds of prey,Seabirds,Poultry and game,Mammals,Cetacean,Whale,Primates,Rodents,Fish,Amphibian,Reptile,Insects,Octopus,Phylum,Class,Order,Family,Genus,Species,Livestock,Creature,Lion,Penguin
Plants|Mushroom,Fungus,Leaves,Seed,Core,Bark,Trunk,Twig,Branch,Flower,Stem,Roots,Cluster,Fertilizer
Continents|South America,North America,Africa,Asia,Europe,Australia,Antarctica
Countries|Egypt,Mexico,France,Indonesia,Turkey,England,Germany,China,Greece,Brazil,India,North Korea,Malaysia,New Zealand,Nigeria,Pakistan,Singapore,Switzerland,United Kingdom,Italy,Dominican Republic,Philippines,Denmark
Languages|Linguistics,Bilingual,Trilingual,Polyglot,Portuguese,Mandarin,Bengali,Chinese,Hindi,Russian,Japanese,German,Punjabi,Thai,Persian,Filipino,French,Italian,Greek
Architecture and buildings|Dome,Palace,Fort,Castle,Glasshouse,Pyramid,Log cabin,Lighthouse,Hut,Skyscraper,Sculpture
Homes|Semi-detached house,Duplex,Terraced house,Town house,Row house,Bungalow,Thatched cottage,Mobile home,Houseboat,Block of flats,Apartment building,Condominium,Chimney,Bedroom,Basement,Landlord,Tenant,Rent,Lease,Neighborhood,Suburb,Sofa,Coffee table,Dormitory,Storey,Kitchen,Refrigerator,Microwave,Ground floor,Oven,Hallway,Insurance
In the city|Cities,Street,Lane,City centre,Central station,Car park,Department store,Bridge,Temple,Embassy,Road system,Hospital,Garden,Avenue
Workplaces|Clinic,Dentist,Reception,Appointment,Staff selection,Colleague,Workshop,Showroom,Information desk,Employer,Employment,Unemployed,Technical cooperation,Team leaders,Stress,Ability,Vision,Confidence,Employee,Internship
Rating and qualities|Reasonable,Satisfactory,Dangerous,Safe,Strongly recommended,Poor quality,Satisfied,Disappointed,Efficient,Luxurious,Colored,Spotted,Striped,Expensive,Cheap
Touring|Tourist guided tour,Ticket office,Souvenir,Trip,Guest,Reservation,View,Culture,Memorable,Single,Double-bedded room,Picnic,Tourist attraction,Hostel,Suite,Aquarium
Verbs|Train,Develop,Collect,Supervise,Mark,Edit,Revise,Exhibit,Donate,Surpass,Register,Support,Hunt,Persuade,Concentrate,Discuss,Suggest,Arrange,Borrow,Immigrate,Review,Learn,Touch
Adjectives|Energetic,Social,Ancient,Necessary,Fantastic,Exciting,Fabulous,Dull,Comfortable,Convenient,Suitable,Affordable,Voluntary,Mandatory,Compulsory,Temporary,Permanent,Immense,Vast,Salty,Extinct,Vulnerable,Pessimistic,Optimistic,Realistic,Practical,Knowledgeable,Flexible,Confident,Western,Intensive,Tranquil,Spectacular,Intact,Various
Hobbies|Orienteering,Caving,Spelunking,Archery,Ice skating,Scuba-diving,Snorkeling,Skateboarding,Bowls,Darts,Golf,Billiards,Photography,Painting,Pottery,Woodcarving,Gardening,Stamp collection,Embroidery,Climbing,Chess,Parachute
Sports|Cricket,Baseball,Basketball,Rugby,Soccer,American football,Hockey,Swimming,Tennis,Squash,Badminton,Ping-pong,Field,Court,Pitch,Stadium,Team,Discus,Javelin,Hammer,High jump,Horse racing,Show jumping,Polo,Cycling,Gymnasium,Athlete,Gym,Extreme sports,Paragliding,Hang-gliding,Skydiving,Abseiling,Snowboarding,Bungee jumping,Surfing,Windsurfing,Jet-skiing,Bodyboarding,White-water rafting,Kitesurfing,Mountain biking,Jogging,Press-up,Push-up,Barbell,Treadmill,Judo,Recreation,Snooker,Walking,Championship,Canoeing,Refreshment
Shapes|Square,Rectangular,Triangular,Polygon,Oval,Spherical,Spiral,Circular,Curved,Cylindrical
Measurement|Width,Length,Altitude,Imperial system,Metric system,Mass,Depth,Breadth,Height,Three dimensions,Frequency
Transportations|Cargo plane,Shipment,Container ship,Boat,Lifeboat,Ferry,Hovercraft,Hydrofoil,Liner,Canal boat,Narrowboat,Dinghy sailing,Sailboat,Paddle steamer,Cabin cruiser,Rowing boat,Rowboat,Kayak,Canoe,Punt,Gondola,Aircraft,Helicopter,Seaplane,Airship,Hot-air balloon,Airport,Crew,Passenger,Platform,Hire a car,Automobile
Vehicles|Double-decker bus,Single-decker,Minibus,School bus,Coach,Truck,Tanker,Van,Lorry,Transporter,Forklift truck,Tow truck,Breakdown truck,Pickup,Jeep,Caravan,Camper,Tractor,Taxi,Cab,Tram,Underground,Subway,Steam train,Freight train,Goods train
Weather|Humid,Hot,Sticky,Breeze,Chilly,Cold,Cool,Dry,Dusty,Freezing,Warm,Wet,Weather forecast,Antenna,Moisture
Places|Local library,Swimming pool,Cafeteria,Cottage,Parliament,Accommodation,Restaurant,Canteen,Cafe,Bookshop,Sports centre,City council,Dance studio,Park,Conversation club,Kindergarten
Equipment and tools|Helmet,Light,Musical instrument,Cassette,Silicon chip,Digital monitor,Gadget,Device,Screen,Brakes,Wheels,Mechanical pencil,Disk,Backpack
The arts and media|Opera,Orchestra,Concert,Symphony,Press,Conductor,Vocalist,Audience,Festival,Carnival,Exhibition,Classical music,Theatre,Cinemas,Art gallery,Museum,Ballet,Television,Radio,Graphics,Newspaper
Materials|Fur,Metal,Steel,Aluminum,Copper,Rubber,Plastic,Ceramics,Glass,Cement,Stone,Textile,Cotton,Fabric,Wool,Leather,Bone,Paper,Lumber/wood,Glue,Composite,Fiberglass,Concrete,Wax,Wood,Silver,Gold,Feather
Works and jobs|Occupation,Profession,Designer,Decorator,Architect,Engineer,Manager,Waitress,Waiter,Teacher,Vacancy,Professor,Specialist,Psychologist,Volunteer,Freelance,Secretary,Craftsman,Work experience,Curriculum vitae,Mail address,Receptionist,Pilot,Guard,Flight attendant,Lecturer,Office assistant,Clerk,Accountant,Cashier,Captain
Color|Blue,White,Orange,Green,Grey,Black,Red,Yellow,Purple,Brown,Pink
Expressions and time|Three times,Three times per week,A gap year,Full-time,Part-time,Midday,Midnight,Millennium,Century,Decade,Fortnight
Other|Passport photo,State,Government,Individual,Variety,Private sector,Practice,Gender,Creativity,Original inhabitant,Indigenous,Demonstration,Strike,Entrance,Circuit,Guarantee,Dialogue,Commerce,Carriage,Narrative,Chocolate,Satellite,Decision,Prototype,Attitude,Daily routine,Personal fulfillment,Activity,Recipient,Ultrasound,Pedestrian safety,Traffic jams,Procedures,Creation,Prize,Junior,Senior,Opportunity,Driving license,Process,Literary,Man-made,Republicans,Umbrella,Frequently updated,Waiting list,Sewer systems,Liberal democracy,Democrats,Lunar calendar,Libertarian,Burger,Videos,Nature conservation,Life expectancy,Fund-raising event,Magnet,Dialect,Ramification,Straight,Farewell,Welfare,Encyclopedia,Evolution,Revolution,Illiteracy,Robot,Proficiency,Sufficient`;
